#!/usr/bin/env python

import sys

from arl_muscle_tester.muscle_tester import MuscleTester
from rqt_gui.main import Main

plugin = 'arl_muscle_tester.muscle_tester.MuscleTester'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=MuscleTester.add_arguments))
